FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]
RUN mkdir /code
WORKDIR /code
ADD requirements.txt requirements-dev.txt /code/
RUN pip install -r requirements-dev.txt
COPY scripts/start*.sh /
COPY . /code/
