# Generated by Django 2.2.5 on 2019-09-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ASIATIC', 'Asiatic'), ('AMERICAN', 'American'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('FRENCH', 'French'), ('ITALIAN', 'Italian'), ('INDIAN', 'Indian'), ('CHINESE', 'Chinese'), ('JAPAN', 'Japan'), ('MEXICAN', 'Mexican'), ('TAPAS', 'Tapas'), ('FISH', 'Fish'), ('MEAT', 'Meat'), ('BIO', 'Bio')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Restaurant Name')),
                ('website', models.URLField(blank=True, max_length=256, null=True, unique=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active ?')),
                ('from_google', models.BooleanField(default=False, verbose_name='Place from Google')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('formatted_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Formatted address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('google_place_id', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Google Place Id')),
                ('google_map_url', models.URLField(blank=True, max_length=256, null=True, unique=True, verbose_name='Google Map URL')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='location.City', verbose_name='City')),
                ('cook_types', models.ManyToManyField(related_name='restaurants', to='place.CookType', verbose_name='Cook Types')),
            ],
        ),
        migrations.CreateModel(
            name='OpenHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=15, verbose_name='Week Day')),
                ('open_hour', models.TimeField(blank=True, verbose_name='Open Hour')),
                ('close_hour', models.TimeField(blank=True, verbose_name='Close Hour')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_hours', to='place.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'week_day', 'open_hour', 'close_hour')},
            },
        ),
    ]
