# Generated by Django 2.2.5 on 2019-09-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='is_active',
            new_name='is_closed',
        ),
    ]
