# Generated by Django 2.2.6 on 2019-10-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('place', '0004_auto_20190921_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='main_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='photos.Photo', verbose_name='Main Photo'),
        ),
    ]
