# Generated by Django 2.2.6 on 2019-10-11 15:45

from django.db import migrations, models


COOK_TYPES = [
    ("Asiatic", "Asiatique"),
    ("American", "Américaine"),
    ("Vegetarian", "Végétarienne"),
    ("Vegan", "Vegan"),
    ("French", "Française"),
    ("Italian", "Italienne"),
    ("Indian", "Indienne"),
    ("Chinese", "Chinoise"),
    ("Japan", "Japonaise"),
    ("Mexican", "Mexicaine"),
    ("Tapas", "Tapas"),
    ("Fish", "Poisson"),
    ("Meat", "Viande"),
    ("Bio", "Bio"),
    ("Fastfood", "Restauration rapide"),
]


def populate_cook_types(apps, schema_editor):
    CookType = apps.get_model("place", "CookType")
    for cook_type in COOK_TYPES:
        c, _created = CookType.objects.get_or_create(
            name_en=cook_type[0], name_fr=cook_type[1]
        )
        c.save()


class Migration(migrations.Migration):

    dependencies = [("place", "0005_restaurant_main_photo")]

    operations = [
        migrations.AddField(
            model_name="cooktype",
            name="name_en",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cooktype",
            name="name_fr",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cooktype", name="name", field=models.CharField(max_length=20)
        ),
        migrations.RunPython(populate_cook_types),
    ]
