# Generated by Django 2.2.6 on 2019-11-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_restaurant_price_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Restaurant Description'),
        ),
    ]
