# Generated by Django 2.2.6 on 2019-11-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Restaurant Description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Restaurant Description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(max_length=75, null=True, verbose_name='Restaurant Name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_fr',
            field=models.CharField(max_length=75, null=True, verbose_name='Restaurant Name'),
        ),
    ]
