# Generated by Django 2.2.6 on 2019-11-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20191005_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Is Accepted ?')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_friendships', to='user.UserProfile', verbose_name='User Sending Invitation')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_friendships', to='user.UserProfile', verbose_name='User Receiving Invitation')),
            ],
            options={
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
