# Generated by Django 2.2.6 on 2019-10-05 13:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20190921_1333'),
        ('user', '0001_initial'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='last_time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last time update'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='last_time_user_eat_in',
            field=models.DateField(blank=True, null=True, verbose_name='Last time user eat in'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='note',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='User Note'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Recommendation Score'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='Recommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user_profile', 'restaurant')},
        ),
    ]
