# Generated by Django 2.2.6 on 2019-11-09 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20191005_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='note',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Recommendation Score'),
        ),
    ]
