# Generated by Django 2.2.5 on 2019-09-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='Week Day')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=256, null=True, unique=True)),
                ('google_photo_reference', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Google Photo Reference')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='place.Restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
