# Generated by Django 2.2.6 on 2019-10-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20190921_1333'),
        ('recommendation', '0002_auto_20191005_1329'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommendations',
            field=models.ManyToManyField(through='recommendation.Recommendation', to='place.Restaurant'),
        ),
    ]
