# Generated by Django 2.2.6 on 2019-10-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='recommendations',
            new_name='restaurants',
        ),
    ]
